# Generated by Django 6.0.1 on 2026-01-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="priority",
            field=models.CharField(
                choices=[("BAIXA", "BAIXA"), ("MÉDIA", "MÉDIA"), ("ALTA", "ALTA")],
                default="BAIXA",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACABAMENTO", "ACABAMENTO"),
                    ("AGUARDANDO", "AGUARDANDO"),
                    ("ALTERAÇÃO", "ALTERAÇÃO"),
                    ("APROVADO", "APROVADO"),
                    ("CANCELADO", "CANCELADO"),
                    ("CONCLUÍDO", "CONCLUÍDO"),
                    ("CONF PASTA USINAGEM", "CONF PASTA USINAGEM"),
                    ("DISPOSITIVO", "DISPOSITIVO"),
                    ("LIBERADO", "LIBERADO"),
                    ("MONTAR PASTA USINAGEM", "MONTAR PASTA USINAGEM"),
                    ("NÃO INICIADO", "NÃO INICIADO"),
                    ("ORÇAMENTO", "ORÇAMENTO"),
                    ("PARADO", "PARADO"),
                    ("PRODUÇÃO", "PRODUÇÃO"),
                    ("PROJETO", "PROJETO"),
                    ("REVISÃO", "REVISÃO"),
                    ("USINAGEM", "USINAGEM"),
                ],
                default="PROJETO",
                max_length=30,
            ),
        ),
    ]
