# Generated by Django 6.0.1 on 2026-01-10 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_alter_project_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Projeto",
                "verbose_name_plural": "Projetos",
            },
        ),
    ]
