# Generated by Django 6.0.1 on 2026-01-10 17:09

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_profile_options_alter_profile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=accounts.models.profile_image_path_location,
            ),
        ),
    ]
