# Generated by Django 6.0.1 on 2026-01-10 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_alter_task_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Tarefa",
                "verbose_name_plural": "Tarefas",
            },
        ),
    ]
